# Generated by Django 2.0.5 on 2018-08-19 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gameApp', '0003_auto_20180819_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userscores',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_id', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
