# Generated by Django 2.0.5 on 2018-08-19 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameApp', '0004_auto_20180819_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='point',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='userscores',
            name='score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
